### ISSUE TITLE
Equivalent for .quadratic in BQM for CQM

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dimod#1154]
I have the following segment :
`# Add quadratic terms

    # x_i-x_j terms
    for i in range(1, len(V) + 1):
        for j in range(i + 1, len(V) + 1):
            key = ('x_' + str(i), 'x_' + str(j))
            cqm.objective.quadratic[key] = 2 * A * np.dot(np.array(I[i - 1]), np.array(I[j - 1]))

    # y_am - y_an terms
    for m in range(1, len(V) + 1):
        for n in range(m + 1, len(V) + 1):
            for a in range(1, len(U) + 1):
                key = ('y_(' + str(a) + ', ' + str(m) + ')', 'y_(' + str(a) + ', ' + str(n) + ')')
                cqm.objective.quadratic[key] = 2 * A * (1 + m * n)

    # x_i-y_am terms
    for i in range(1, len(V) + 1):
        for m in range(1, len(V) + 1):
            for a in range(1, len(U) + 1):
                key = ('x_' + str(i), 'y_(' + str(a) + ', ' + str(m) + ')')
                cqm.objective.quadratic[key] = -2 * A * m * I[i - 1][a - 1]`

And I get this runtime error :
Traceback (most recent call last):
  File "C:\Users\elmm\Desktop\MIT OCW Codes\CQM_2.py", line 105, in <module>
    cqm, x = build_setcover_cqm(U, V)
  File "C:\Users\elmm\Desktop\MIT OCW Codes\CQM_2.py", line 64, in build_setcover_cqm
    cqm.objective.quadratic[key] = 2 * A * np.dot(np.array(I[i - 1]), np.array(I[j - 1]))
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dimod\views\quadratic.py", line 217, in __setitem__
    self._model.set_quadratic(*uv, bias)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dimod\decorators.py", line 475, in wrapper
    return method(*args, **kwargs)
  File "dimod\quadratic\cyqm\cyqm_template.pyx.pxi", line 681, in dimod.quadratic.cyqm.cyqm_float64.cyQM_template.set_quadratic
  File "dimod\cyvariables.pyx", line 306, in dimod.cyvariables.cyVariables.index
ValueError: unknown variable 'x_1'

How can I resolve this error?

**Comment by arcondello** [comment]
You cannot set the biases for variables that have not been added to the model. Something like
```python
objective.add_variable('BINARY', 'x_1')
objective.add_variable('BINARY', 'x_2')
objective.quadratic['x_1', 'x_2'] = 1
```
will work

**Comment by ACE07-Sev** [comment]
Hi I tried but got this error :
Traceback (most recent call last):
  File "C:\Users\elmm\Desktop\MIT OCW Codes\CQM_2.py", line 108, in <module>
    cqm, x = build_setcover_cqm(U, V)
  File "C:\Users\elmm\Desktop\MIT OCW Codes\CQM_2.py", line 66, in build_setcover_cqm
    cqm.objective.quadratic[key] = 2 * A * np.dot(np.array(I[i - 1]), np.array(I[j - 1]))
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dimod\views\quadratic.py", line 217, in __setitem__
    self._model.set_quadratic(*uv, bias)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dimod\decorators.py", line 475, in wrapper
    return method(*args, **kwargs)
  File "dimod\quadratic\cyqm\cyqm_template.pyx.pxi", line 681, in dimod.quadratic.cyqm.cyqm_float64.cyQM_template.set_quadratic
  File "dimod\cyvariables.pyx", line 306, in dimod.cyvariables.cyVariables.index
ValueError: unknown variable 'x_1'

`import os

os.chdir('..')
from dimod import ConstrainedQuadraticModel, Integer, BinaryQuadraticModel
from dwave.system import LeapHybridCQMSampler
from dimod import ExactSolver
from neal import SimulatedAnnealingSampler
from itertools import combinations
from dwave.system import LeapHybridSampler
import numpy as np
import pandas as pd


# from utils.data import read_inventory_optimization_data
# from services.classical_optimizers import binary_supplier_optimizer

def build_setcover_cqm(U, V, verbose=False):
    """Construct CQM for the set cover problem
    Args:
        U (array-like):
            A set of elements defining the universe
        V (array of sets):
            Array of subsets
    Returns:
        Constrained quadratic model instance
        x: variable
    """

    # Create indicator variables
    I = []
    for i in range(len(V)):
        I.append([1 if U[a] in V[i] else 0 for a in range(len(U))])

    if verbose:
        print('Indicator variables: I_i,a', I)

    # Lagrange multipliers A>B>0
    A = 2
    B = 1

    ##@  Constrained Quadratic Model @##
    cqm = ConstrainedQuadraticModel()

    # Add linear terms
    # x linear terms
    [cqm.add_variable('x_' + str(i + 1), 'INTEGER') for i in range(0, len(V))]
    x = [cqm.fix_variable('x_' + str(i + 1), A * sum(I[i]) + B) for i in range(0, len(V))]
    if verbose:
        print('x variables:', x)

    # y_am linear terms
    y = []
    for a in range(1, len(U) + 1):
        [cqm.add_variable('y_(' + str(a) + ', ' + str(m) + ')', 'INTEGER') for m in range(1, len(V) + 1)]
        y.append(
            [cqm.fix_variable('y_(' + str(a) + ', ' + str(m) + ')', A * (m ** 2 - 1)) for m in range(1, len(V) + 1)])
    if verbose:
        print('y variables:', y)

    # Add quadratic terms

    # x_i-x_j terms
    for i in range(1, len(V) + 1):
        for j in range(i + 1, len(V) + 1):
            key = ('x_' + str(i), 'x_' + str(j))
            cqm.objective.quadratic[key] = 2 * A * np.dot(np.array(I[i - 1]), np.array(I[j - 1]))

    # y_am - y_an terms
    for m in range(1, len(V) + 1):
        for n in range(m + 1, len(V) + 1):
            for a in range(1, len(U) + 1):
                key = ('y_(' + str(a) + ', ' + str(m) + ')', 'y_(' + str(a) + ', ' + str(n) + ')')
                cqm.objective.quadratic[key] = 2 * A * (1 + m * n)

    # x_i-y_am terms
    for i in range(1, len(V) + 1):
        for m in range(1, len(V) + 1):
            for a in range(1, len(U) + 1):
                key = ('x_' + str(i), 'y_(' + str(a) + ', ' + str(m) + ')')
                cqm.objective.quadratic[key] = -2 * A * m * I[i - 1][a - 1]
    return cqm, x


def solve_cqm(cqm, x, **kwargs):
    sampler = LeapHybridCQMSampler()
    response = sampler.sample_cqm(cqm, **kwargs)
    energies = response.record.energy
    best_energy = energies[0]
    best_solution = response.first.sample
    best_solution = [best_solution[i] for i in x]
    print(best_solution)
    print(f'Energy: {best_energy}')

    return best_solution, best_energy


# Define a simple set cover problem
U = list(set(np.random.randint(10, size=10)))

V = [set(U[i] for i in np.random.randint(len(U), size=(8))) for j in range(5)]

print('The universe is', U)
print('Number of elements in the universe: {:d}'.format(len(U)))

print('There are {:d} collections:'.format(len(V)), V)
print('Number of sets: N={:d}'.format(len(V)))

cqm, x = build_setcover_cqm(U, V)
best_solution = solve_cqm(cqm, x)

cqm, x = build_setcover_cqm(U, V)
best_solution = solve_cqm(cqm, x)
`
I have created the variables before this. Can please see what I should correct to fix this?

**Comment by arcondello** [comment]
> File "C:\Users\elmm\Desktop\MIT OCW Codes\CQM_2.py", line 66, in build_setcover_cqm
cqm.objective.quadratic[key] = 2 * A * np.dot(np.array(I[i - 1]), np.array(I[j - 1]))

You are again setting a quadratic bias for variables that do not yet exist. Also, can you please review [code formatting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) and how to create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I am having trouble parsing your questions and code snippets

**Comment by ACE07-Sev** [comment]
here is picture of the model, I was able to fix that
![image](https://user-images.githubusercontent.com/73689800/159200618-073d4ea9-a392-42a2-9b74-c9c194cc628a.png)

**Comment by ACE07-Sev** [comment]
I resolved the run-time errors and now just get the error for not having token for using HybridCQMSolver. Would it be possible if I send you the code I have right now and you kindly review to see if it's correct? It's for an incredibly important assignment and I really need to make sure it's correct. can I please email the code to you?
