### ISSUE TITLE
Please add to README how to run tests

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dimod#1234]
pytest doesn't find any tests.

**Comment by arcondello** [comment]
```bash
python -m unittest
```
will run the test with [unittest](https://docs.python.org/3/library/unittest.html).

I have not personally used pytest, but [I believe](https://docs.pytest.org/en/7.1.x/how-to/unittest.html)
```bash
pytest tests
```
should also work.

Note, that to you will also need to build the C++/Cython parts of dimod. Usually done with
```bash
python setup.py build_ext --inplace
```
or
```bash
pip install .
```

**Comment by yurivict** [comment]
Test fails for some reason:
```
 /usr/local/bin/python3.9 -m unittest  -v
dimod (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: dimod (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: dimod
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/science/py-dimod/work-py39/dimod-0.11.4/dimod/__init__.py", line 18, in <module>
    from dimod.constrained import *
  File "/disk-samsung/freebsd-ports/science/py-dimod/work-py39/dimod-0.11.4/dimod/constrained.py", line 38, in <module>
    from dimod.binary.binary_quadratic_model import BinaryQuadraticModel, Binary, Spin, as_bqm
  File "/disk-samsung/freebsd-ports/science/py-dimod/work-py39/dimod-0.11.4/dimod/binary/__init__.py", line 15, in <module>
    from dimod.binary.binary_quadratic_model import *
  File "/disk-samsung/freebsd-ports/science/py-dimod/work-py39/dimod-0.11.4/dimod/binary/binary_quadratic_model.py", line 41, in <module>
    from dimod.binary.cybqm import cyBQM_float32, cyBQM_float64
  File "/disk-samsung/freebsd-ports/science/py-dimod/work-py39/dimod-0.11.4/dimod/binary/cybqm/__init__.py", line 15, in <module>
    from dimod.binary.cybqm.cybqm_float32 import cyBQM_float32
ModuleNotFoundError: No module named 'dimod.binary.cybqm.cybqm_float32'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

It is run from repo root.
When it is run from dimod/ - no tests are found.

**Comment by arcondello** [comment]
The tests are located under [tests/](https://github.com/dwavesystems/dimod/tree/main/tests) which is why running under `dimod/` does not find them. When running from repo root, you need to build the package in place. With `python setup.py build_ext --inplace`. You could also run the tests from within `tests/`.
