### ISSUE TITLE
Can't install dimod in virtual environment

### ISSUE THREAD

**Issue by kcLin2708** [dwavesystems/dimod#1236]
**Description**
Hi there, I'm building a django bakckend and just run pip install dimod in virtueal enviroment. However, I can't install it and just got the following error.
```
Requirement already satisfied: pip in c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages (21.2.3)
Collecting pip
  Using cached pip-22.2.2-py3-none-any.whl (2.0 MB)Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.3
    Uninstalling pip-21.2.3:
      Successfully uninstalled pip-21.2.3
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\tws80\\AppData\\Local\\Temp\\pip-uninstall-anjj51ut\\pip.exe'
Check the permissions.

(venv) PS C:\Users\tws80\Documents\github\django_app> pip install dimod        
WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
Collecting dimod
  Using cached dimod-0.11.5.tar.gz (1.9 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [123 lines of output]
      WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
      Collecting setuptools>=46.4.0
        Using cached setuptools-65.2.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting Cython<3.0,>=0.29.21
        Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.8.16-py3-none-any.whl (3.9 kB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [86 lines of output]
        Running from numpy source directory.
        setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
          run_build = parse_setuppy_commands()
        Processing numpy/random\_bounded_integers.pxd.in
        Processing numpy/random\bit_generator.pyx
        Processing numpy/random\mtrand.pyx
        Processing numpy/random\_bounded_integers.pyx.in
        Processing numpy/random\_common.pyx
        Processing numpy/random\_generator.pyx
        Processing numpy/random\_mt19937.pyx
        Processing numpy/random\_pcg64.pyx
        Processing numpy/random\_philox.pyx
        Processing numpy/random\_sfc64.pyx
        Cythonizing sources
        blas_opt_info:
        blas_mkl_info:
        'gcc' is not recognized as an internal or external command,
        operable program or batch file.
        Traceback (most recent call last):
          File "C:\Users\tws80\Documents\github\django_app\venv\lib\python3.9\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
            main()
          File "C:\Users\tws80\Documents\github\django_app\venv\lib\python3.9\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Users\tws80\Documents\github\django_app\venv\lib\python3.9\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "C:\Users\tws80\AppData\Local\Temp\pip-build-env-h_aabunp\overlay\lib\python3.9\site-packages\setuptools\build_meta.py", line 157, in prepare_metadata_for_build_wheel   
            self.run_setup()
          File "C:\Users\tws80\AppData\Local\Temp\pip-build-env-h_aabunp\overlay\lib\python3.9\site-packages\setuptools\build_meta.py", line 248, in run_setup
            super(_BuildMetaLegacyBackend,
          File "C:\Users\tws80\AppData\Local\Temp\pip-build-env-h_aabunp\overlay\lib\python3.9\site-packages\setuptools\build_meta.py", line 142, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 508, in <module>
            setup_package()
          File "setup.py", line 500, in setup_package
            setup(**metadata)
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\core.py", line 135, in setup
            config = configuration()
          File "setup.py", line 174, in configuration
            config.add_subpackage('numpy')
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\misc_util.py", line 1018, in add_subpackage
            config_list = self.get_subpackage(subpackage_name, subpackage_path,
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\misc_util.py", line 984, in get_subpackage
            config = self._get_configuration_from_setup_py(
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
            config = setup_module.configuration(*args)
          File "numpy\setup.py", line 8, in configuration
            config.add_subpackage('core')
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\misc_util.py", line 1018, in add_subpackage
            config_list = self.get_subpackage(subpackage_name, subpackage_path,
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\misc_util.py", line 984, in get_subpackage
            config = self._get_configuration_from_setup_py(
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
            config = setup_module.configuration(*args)
          File "numpy\core\setup.py", line 762, in configuration
            blas_info = get_info('blas_opt', 0)
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 485, in get_info
            return cl().get_info(notfound_action)
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 746, in get_info
            self.calc_info()
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 1914, in calc_info
            if self._calc_info(blas):
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 1893, in _calc_info
            return getattr(self, '_calc_info_{}'.format(name))()
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 1830, in _calc_info_mkl
            info = get_info('blas_mkl')
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 485, in get_info
            return cl().get_info(notfound_action)
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 746, in get_info
            self.calc_info()
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 1197, in calc_info
            info = self.check_libs2(lib_dirs, mkl_libs)
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 902, in check_libs2
            exts = self.library_extensions()
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 861, in library_extensions
            c = customized_ccompiler()
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\system_info.py", line 202, in customized_ccompiler        
            global_compiler = _customized_ccompiler()
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\__init__.py", line 49, in customized_ccompiler
            c = ccompiler.new_compiler(plat=plat, compiler=compiler, verbose=verbose)       
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\ccompiler.py", line 765, in new_compiler
            compiler = klass(None, dry_run, force)
          File "C:\Users\tws80\AppData\Local\Temp\pip-install-8_enx8al\numpy_d9e9e40004da4f77858dd463a0473f56\numpy\distutils\mingw32ccompiler.py", line 61, in __init__
            distutils.cygwinccompiler.CygwinCCompiler.__init__ (self, verbose,
          File "C:\Program Files\Inkscape\lib\python3.9\distutils\cygwinccompiler.py", line 131, in __init__
            if self.ld_version >= "2.10.90":
        TypeError: '>=' not supported between instances of 'NoneType' and 'str'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
      WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
      WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.      
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.        
WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\tws80\documents\github\django_app\venv\lib\python3.9\site-packages)
```

**Steps To Reproduce**
1. Create a virtual enviroment by: python -m venv venv
2. Activate virutal environment by: .\venv\bin\activate
3. pip install dimod

**Expected Behavior**
I should able to install dimod package.

**Environment**
 - OS: Windows 11
 - Python version: 3.9.7
 - pip: 22.2.2

**Additional Context**
Add any other background information about the problem.

**Comment by arcondello** [comment]
Hi @kcLin2708 , I am taking a look. Also, I made a minor edit to your original comment for formatting, hope that's ok!

**Comment by arcondello** [comment]
It actually appears that the error appears when it's trying to install `numpy` before trying to install `dimod`.

I am surprised that it's installing the source distributions of numpy/dimod rather than the wheels though. You should be on a OS/Python supported by both. Can you tell me your `setuptools` version?

**Comment by kcLin2708** [comment]
Hi Alexander,
Thank you for your quick reply. I tried to install numpy in venv but still get almost the same error. I suppose this problem is due to my windows environment. I'll try to debug it, thanks!

**Comment by arcondello** [comment]
Hi @kcLin2708 , were you able to resolve this? If so can we close this issue?

**Comment by kcLin2708** [comment]
Yes, you can close it. Thanks!
