### ISSUE TITLE
Constraint labels can break CQM (de-)serialization

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#1358]
**Description**

Currently `CQM.to_file()` encodes constraint labels with [`json.dumps`](https://github.com/dwavesystems/dimod/blob/85f5bafd514f32585666e5de4c75db9b53444626/dimod/constrained/constrained.py#L1786), allowing characters that are illegal in file names, like `/`. That becomes a problem only when trying to extract the CQM zip file.

However, `CQM.from_file()` assumes forward slashes are **not allowed** in file names and that `/` is used **only** as (POSIX) path separator:

https://github.com/dwavesystems/dimod/blob/85f5bafd514f32585666e5de4c75db9b53444626/dimod/constrained/constrained.py#L1071-L1073

Consequently, decoding CQMs with slashes in constraint labels will fail.

**Steps To Reproduce**
```
>>> import dimod
>>> cqm = dimod.CQM()
>>> cqm.add_constraint(dimod.Binary() == 1, label='a/b')
'a/b'
>>> dimod.CQM.from_file(cqm.to_file())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radomir/work/dimod/env311/lib/python3.11/site-packages/dimod/constrained/constrained.py", line 1078, in from_file
    label = deserialize_variable(json.loads(constraint))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radomir/.pyenv/versions/3.11.4/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radomir/.pyenv/versions/3.11.4/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radomir/.pyenv/versions/3.11.4/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1 (char 0)
```

**Expected Behavior**

Serializing CQMs with forward slashes (and some other unicode characters, like NULL) should be forbidden. Or at least such labels should be renamed, either on constraint creation, or cqm serialization.

**Environment**
 - any OS, any python
 - reproduces with latest `dimod==0.12.12`

**Comment by matti-sarjala** [comment]
A useful design boundary here may be to keep constraint-label identity separate from archive path encoding.

A constraint label is user-facing model metadata. A ZIP member path is an implementation detail. The bug appears when the same string is allowed to serve both roles without an escaping or validation contract.

Possible behavior contract:

1. Constraint labels may remain general user labels at the model level.
2. The file format should either:
   - encode/escape labels so they are safe as archive members, or
   - reject labels that cannot be represented safely before serialization.
3. `to_file()` should fail early with a clear error if a label is not serializable under the chosen format.
4. `from_file()` should not have to guess whether `/` means part of a label or part of the archive structure.
5. A regression test should cover at least:
   - a normal label,
   - a label containing `/`,
   - a label containing a platform/path-sensitive character,
   - round-trip preservation or clear rejection.

I would lean toward treating this as a serialization-format contract rather than a general restriction on CQM labels, unless there is already an intended rule that labels must be path-safe. That keeps the optimization model identity independent of the storage layout.
