### ISSUE TITLE
SamplerABCMeta fails in Python 3.7

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#199]
```
Python 3.7.0b3+ (heads/3.7:74735e2, Apr  3 2018, 18:20:19) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dimod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmp.8MLzTlLNBw/lib/python3.7/site-packages/dimod/__init__.py", line 3, in <module>
    from dimod.core import *
  File "/tmp/tmp.8MLzTlLNBw/lib/python3.7/site-packages/dimod/core/__init__.py", line 1, in <module>
    from dimod.core.composite import *
  File "/tmp/tmp.8MLzTlLNBw/lib/python3.7/site-packages/dimod/core/composite.py", line 51, in <module>
    from dimod.core.sampler import Sampler
  File "/tmp/tmp.8MLzTlLNBw/lib/python3.7/site-packages/dimod/core/sampler.py", line 95, in <module>
    @add_metaclass(abc.SamplerABCMeta)
  File "/tmp/tmp.8MLzTlLNBw/lib/python3.7/site-packages/six.py", line 847, in wrapper
    return metaclass(cls.__name__, cls.__bases__, orig_vars)
  File "/tmp/tmp.8MLzTlLNBw/lib/python3.7/site-packages/dimod/abc.py", line 37, in __new__
    cls._abc_negative_cache_version = ABCMeta._abc_invalidation_counter
AttributeError: type object 'ABCMeta' has no attribute '_abc_invalidation_counter'
```

**Comment by randomir** [comment]
In python 3.7, private `ABCMeta._abc_invalidation_counter` doesn't exist anymore.
