### ISSUE TITLE
Deserialization fails for 'energy=None'

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#292]
(De-)serialization works when `energy=<number>`:

```
>>> import dimod, json
>>> s = dimod.SampleSet.from_samples([[1,1,1,1], [0,0,0,0]], energy=0, vartype='BINARY')
>>> dimod.SampleSet.from_serializable(json.loads(json.dumps(s.to_serializable())))
SampleSet(rec.array([(0, 1, [1, 1, 1, 1]), (0, 1, [0, 0, 0, 0])],
          dtype=[('energy', '<i8'), ('num_occurrences', '<i8'), ('sample', 'i1', (4,))]), [0, 1, 2, 3], {}, 'BINARY')
```

but fails when `energy=None`:

```
>>> s = dimod.SampleSet.from_samples([[1,1,1,1], [0,0,0,0]], energy=None, vartype='BINARY')
>>> dimod.SampleSet.from_serializable(json.loads(json.dumps(s.to_serializable())))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmp.7ka5nvaHmX/lib/python3.5/site-packages/dimod/sampleset.py", line 768, in from_serializable
    return sampleset_decode_hook(obj, cls=cls)
  File "/tmp/tmp.7ka5nvaHmX/lib/python3.5/site-packages/dimod/io/json.py", line 138, in sampleset_decode_hook
    record = _unpack_record(dct['record'], vartype)
  File "/tmp/tmp.7ka5nvaHmX/lib/python3.5/site-packages/dimod/io/json.py", line 94, in _unpack_record
    raw = np.frombuffer(base64.b64decode(data['data']), dtype=dtype)
ValueError: cannot create an OBJECT array from memory buffer
```

**Comment by arcondello** [comment]
This is actually a bug with `SampleSet`, None should not be an allowed energy.

**Comment by randomir** [comment]
But I like having `None` for energy. It's explicit about the fact you (sometimes) don't care about the energy of your samples.
