### ISSUE TITLE
FileView deserialization fails on unhashable variable labels

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#598]
For example:
```
import dimod, dimod.serialization.fileview

bqm = dimod.BQM.from_ising({(0,1): 1}, {})
data = dimod.serialization.fileview.FileView(dimod.AdjArrayBQM(bqm)).read()
bqm2 = dimod.serialization.fileview.load(data)
```
fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radomir/work/dwave-cloud-client/hss/lib/python3.7/site-packages/dimod/serialization/fileview.py", line 324, in load
    return cls._load(fp, data, offset=offset)
  File "dimod/bqm/adjarraybqm.pyx", line 491, in dimod.bqm.adjarraybqm.cyAdjArrayBQM._load
TypeError: unhashable type: 'list'
```

**Comment by arcondello** [comment]
Oops, accidentally pushed to `dev`. Anyway, closed by https://github.com/dwavesystems/dimod/commit/72ee92017fd0c582571cdfbdddf68deb8b091498.
