### ISSUE TITLE
`import dimod` fails on Python 3.7.10 with dimod 0.10.0

### ISSUE THREAD

**Issue by j-i-k-o** [dwavesystems/dimod#901]
**Description**
`import dimod` on Python 3.7.10 causes a `TypeError` exception.
```shell
❯ python           
Python 3.7.10 (default, Jul 16 2021, 19:59:05) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dimod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/__init__.py", line 18, in <module>
    from dimod.bqm import *
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/bqm/__init__.py", line 15, in <module>
    from dimod.bqm.adjvectorbqm import AdjVectorBQM
  File "dimod/bqm/adjvectorbqm.pyx", line 38, in init dimod.bqm.adjvectorbqm
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/core/__init__.py", line 15, in <module>
    from dimod.core.composite import Composite, ComposedSampler
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/core/composite.py", line 67, in <module>
    from dimod.core.sampler import Sampler
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/core/sampler.py", line 110, in <module>
    from dimod.binary_quadratic_model import BinaryQuadraticModel
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/binary_quadratic_model.py", line 17, in <module>
    from dimod.binary.binary_quadratic_model import BinaryQuadraticModel, BQM
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/binary/__init__.py", line 15, in <module>
    from dimod.binary.binary_quadratic_model import *
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/binary/binary_quadratic_model.py", line 30, in <module>
    from numpy.typing import ArrayLike, DTypeLike
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/numpy/typing/__init__.py", line 315, in <module>
    from ._shape import _Shape, _ShapeLike
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/numpy/typing/_shape.py", line 15, in <module>
    _ShapeLike = Union[SupportsIndex, Sequence[SupportsIndex]]
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/typing.py", line 254, in inner
    return func(*args, **kwds)
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/typing.py", line 634, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/typing.py", line 634, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/typing.py", line 142, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got NotImplemented.
>>> 

```

**Steps To Reproduce**
1. install python 3.7.10 on Linux
2. install dimod (with wheel package `dimod-0.10.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl`)
3. `import dimod`

**Expected Behavior**
```shell
Python 3.7.10 (default, Jul 16 2021, 19:59:05) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dimod
>>>
```

**Environment**
 - OS: Arch Linux (with Linux kernel 5.12.10-arch1-1)
 - Python version: 3.7.10

**Comment by hhtong** [comment]
Hi @j-i-k-o, thanks for bringing this up.

What version of numpy are you using? If it’s 1.21, I believe the error is coming directly from numpy: see https://github.com/numpy/numpy/issues/19310. This problem should be fixed by 1.21.1 (see https://github.com/numpy/numpy/pull/19311).

As a temporary fix, you could try downgrading your numpy (should work with 1.20), or try a python >= 3.8.

Hope this helps!

**Comment by j-i-k-o** [comment]
HI @hhtong, thanks for the comment!
```shell
❯ python -m pip show numpy
Name: numpy
Version: 1.21.0
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages
Requires: 
Required-by: dimod
```
Yes, The version of  numpy is 1.21.0.
I'm going to wait until numpy is uploaded to 1.21.1.
Many thanks.

**Comment by j-i-k-o** [comment]
I upgraded numpy to 1.21.1,  which still has a similar error.
```sh
❯ python --version
Python 3.7.10

~
❯ python -m pip show dimod            
Name: dimod
Version: 0.10.2
Summary: A shared API for binary quadratic model samplers.
Home-page: https://github.com/dwavesystems/dimod
Author: D-Wave Systems Inc.
Author-email: tools@dwavesys.com
License: Apache 2.0
Location: /home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages
Requires: numpy
Required-by: 

~
❯ python -m pip show numpy
Name: numpy
Version: 1.21.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages
Requires: 
Required-by: dimod

~
❯ python                  
Python 3.7.10 (default, Jul 16 2021, 19:59:05) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dimod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/__init__.py", line 18, in <module>
    from dimod.bqm import *
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/bqm/__init__.py", line 15, in <module>
    from dimod.bqm.adjvectorbqm import AdjVectorBQM
  File "dimod/bqm/adjvectorbqm.pyx", line 38, in init dimod.bqm.adjvectorbqm
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/core/__init__.py", line 15, in <module>
    from dimod.core.composite import Composite, ComposedSampler
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/core/composite.py", line 67, in <module>
    from dimod.core.sampler import Sampler
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/core/sampler.py", line 110, in <module>
    from dimod.binary_quadratic_model import BinaryQuadraticModel
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/binary_quadratic_model.py", line 17, in <module>
    from dimod.binary.binary_quadratic_model import BinaryQuadraticModel, BQM
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/binary/__init__.py", line 15, in <module>
    from dimod.binary.binary_quadratic_model import *
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/dimod/binary/binary_quadratic_model.py", line 30, in <module>
    from numpy.typing import ArrayLike, DTypeLike
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/numpy/typing/__init__.py", line 316, in <module>
    from ._dtype_like import (
  File "/home/jiko/.pyenv/versions/3.7.10/lib/python3.7/site-packages/numpy/typing/_dtype_like.py", line 95, in <module>
    class _SupportsDType(Generic[_DType_co]):
NameError: name '_DType_co' is not defined
>>> 
````
I suppose the current quick solution is to install `typing_extensions` package since the problem basically comes from typing_extensions in numpy (numpy/numpy#19310)

**Comment by hhtong** [comment]
I've opened an issue on numpy here: https://github.com/numpy/numpy/issues/19521

**Comment by arcondello** [comment]
Closing since NumPy 1.21.2+ is now deployed.
